name: PHP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP version 8
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - run: cd php && php -f Calculator.php
