name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.5.4]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.5"
      - run: cd python && python Calculator.py
